---
apiVersion: v1
kind: Pod
metadata:
  name: dcap-sample
  annotations:
    sgx.intel.com/quote-provider: aesmd
  labels:
    app: dcap-sample
spec:
  restartPolicy: OnFailure
  containers:
    - image: dcap-sample:v1.15
      name: dcap-sample
      resources:
        limits:
          sgx.intel.com/epc: "512Ki"
      workingDir: "/opt/intel/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample/"
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /etc/sgx_default_qcnl.conf
          subPath: sgx_default_qcnl.conf
          name: qplconf
      command: ["/bin/bash"]
      args: ["-c", "SGX_AESM_ADDR=1 ./app"]
  volumes:
    - name: qplconf
      configMap:
        name: qplconf