---
apiVersion: v1
kind: Pod
metadata:
  name: asps-sample
  annotations:
    sgx.intel.com/quote-provider: aesmd
  labels:
    app: asps-sample
spec:
  restartPolicy: OnFailure
#  hostAliases:
#  - ip: "192.168.122.111"
#    hostnames:
#      - pccs.service.com
  containers:
    - image: asp_service:graminev1.2-latest
      name: asps-sample
      resources:
        limits:
          sgx.intel.com/epc: "2Gi"
      workingDir: "/root/CI-Examples/attestation-secret-provision"
      imagePullPolicy: Never
      command: ["/bin/bash"]
      args: ["entrypoint.sh"]
      volumeMounts:
        - name: qplconf
          mountPath: /etc/sgx_default_qcnl.conf
          subPath: sgx_default_qcnl.conf
  volumes:
    - name: qplconf
      configMap:
        name: qplconf
  nodeSelector:
    kubernetes.io/hostname: kubenode1
